# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9899cd54-3eb1-433f-8626-863f2794a01f";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7BA6-548E";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/9899cd54-3eb1-433f-8626-863f2794a01f";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/9899cd54-3eb1-433f-8626-863f2794a01f";
    fsType = "btrfs";
    options = [ "subvol=@swap" ];
  };

  fileSystems."/mnt/renegade" = {
    device = "/dev/disk/by-uuid/88c3b4a1-3d8a-4f4b-910f-269022123125";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "nofail"
      "x-systemd.automount"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
